# Site settings
title: ZongEasy
header-img: "img/autumn2.jpg"
tagline: "宗易"  
description: "在遙遠的地方 一切虔誠終必相遇"  
baseurl: ""
url: "http://blog.zongeasy.com"  

# About/contact
owner: 
  name: "zongeasy"
  email: zongeasy@qq.com
  bio: "明朝即長路 惜取此時心"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: zongeasy
twitter_username: zongeasy  
github_username: zongeasy  
facebook_username: zongeasy 
weibo_username: 宗易ZongEasy 
zhihu_username: zongeasy  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

gems: [jekyll-paginate]
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "zongeasy"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : zongeasy
  disqus :
      short_name : zongeasy

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation